/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Get user todos */
		get: operations["getApi"];
		put?: never;
		/** @description Create todo */
		post: operations["postApi"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["putApiById"];
		post?: never;
		delete: operations["deleteApiById"];
		options?: never;
		head?: never;
		/** @description Patch todo */
		patch: operations["patchApiById"];
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	headers: never;
	parameters: never;
	pathItems: never;
	requestBodies: never;
	responses: never;
	schemas: never;
}
export type $defs = Record<string, never>;
export interface operations {
	deleteApiById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getApi: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Todos list */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	patchApiById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": {
					/** @enum {string} */
					status?: "todo" | "backlog" | "inprogress" | "done" | "cancelled";
					text?: string;
					description?: string;
				};
			};
		};
		responses: {
			/** @description Updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	postApi: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": {
					text: string;
					description: string;
					/** @enum {string} */
					status: "todo" | "backlog" | "inprogress" | "done" | "cancelled";
					startDate: string;
					startTime: string;
					endDate: string;
					endTime: string;
				};
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	putApiById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": {
					text: string;
					description: string;
					/** @enum {string} */
					status: "todo" | "backlog" | "inprogress" | "done" | "cancelled";
					startDate: string;
					startTime: string;
					endDate: string;
					endTime: string;
				};
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
